verifyConditions:
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - semantic-release-docker
publish:
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - path: semantic-release-docker
    name: nbrink91/portfolio