dist: trusty
language: node_js
node_js:
  - "10"
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  chrome: stable
before_install:
  - npm i -g npm@latest
  - npm install -g @angular/cli
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint
    - script: npm run test:ci
    - script: npm run e2e:ci
    - stage: release
      services:
        - docker
      script:
        - npm run build:ci
        - docker build -t ${IMAGE_NAME} .
        - docker images
        - npm run semantic-release
stages:
  - test
  - name: release
    if: branch = master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/