sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  chrome: stable
before_install:
  - npm i -g npm@latest
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run test:ci
      script: npm run e2e:ci
      script: npm run lint
after_success:
  - npm run travis-deploy-once "npm run semantic-release --debug"
  - npm run travis-deploy-once "docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD"
  - npm run travis-deploy-once "docker build -t ${IMAGE_NAME} ."
  - npm run travis-deploy-once "docker push \"${IMAGE_NAME}:latest\" && docker push \"${IMAGE_NAME}:${version}\""
branches:
  except:
    - /^v\d+\.\d+\.\d+$/