sudo: required
dist: trusty
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm run test
  - npm run e2e
  - npm run lint
  - npm run build
notifications:
  email:
    on_failure: change
    on_success: change