dist: trusty
language: node_js
node_js:
  - "10"
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  chrome: stable
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run test:ci
    - script: npm run e2e:ci
    - script: npm run lint
    - stage: release
      services:
        - docker
      script:
        - npm run semantic-release
        - npm run build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t ${IMAGE_NAME} .
        - docker push "${IMAGE_NAME}:latest"
        - docker push "${IMAGE_NAME}:${version}"
stages:
  - test
  - name: release
    if: branch = master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/