sudo: required
dist: trusty
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_install:
  - npm i -g npm@latest
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run test:ci
    - script: npm run e2e:ci
    - script: npm run lint
notifications:
  email:
    on_failure: change
    on_success: change