dist: trusty
language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  chrome: stable
before_install:
  - yarn global add @angular/cli@latest
install:
  - yarn install
jobs:
  include:
    - stage: test
      script: yarn run lint
    - script: yarn run test:ci
    - script: yarn run e2e:ci
    - stage: release
      services:
        - docker
      script:
        - yarn run build:ci
        - docker build -t ${IMAGE_NAME} .
        - docker images
        - yarn run semantic-release
stages:
  - test
  - name: release
    if: branch = master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/